[package]
name = "saddle-character-state-machine-example-controller-3d"
version = "0.1.0"
edition = "2024"
publish = false

[features]
e2e = ["dep:saddle-bevy-e2e"]

[dependencies]
bevy = { workspace = true }
avian3d = { workspace = true }
saddle-character-controller = { workspace = true }
saddle-character-state-machine = { workspace = true }
saddle-character-state-machine-example-support = { path = "../support" }
saddle-pane = { workspace = true }
saddle-bevy-e2e = { workspace = true, optional = true }

[lints]
workspace = true
